### ISSUE TITLE
Clarify licenses for Java/C++ libraries

### ISSUE THREAD

**Issue by shadaj** [juchong/ADIS16448-RoboRIO-Driver#2]
In the Java (https://github.com/juchong/ADIS16448-RoboRIO-Driver/blob/master/Java/com/analog/adis16448/frc/ADIS16448_IMU.java) and C++ (https://github.com/juchong/ADIS16448-RoboRIO-Driver/blob/master/C%2B%2B/src/ADIS16448_IMU.cpp) sources, the header seems to state that the project should be under BSD. However, there is also a license file in the root folder (https://github.com/juchong/ADIS16448-RoboRIO-Driver/blob/master/LICENSE) which is GPLv2.

Did you mean to have the project under GPL, or should it be BSD? Also, where is the origin of the C++ and Java sources?

**Comment by juchong** [comment]
The GPL license was removed. The blanket FRC, BSD license should now prevail.
