### ISSUE TITLE
C++ Errors

### ISSUE THREAD

**Issue by facepalmgamer** [juchong/ADIS16448-RoboRIO-Driver#21]
My team and i have just set up out gyro and were messing with the smartdashboard, and as we deploy the code and enable our robot we get this error in the consol
![image1](https://user-images.githubusercontent.com/30478166/35187958-76ecddae-fdfb-11e7-903f-a01e7f395ffb.jpeg)
so we checked the .h and it was fine but the ADIS16448_IMU.cpp in the src folder had 4 errors 2 being related to the the notify_all at line 239 and 328
![image2](https://user-images.githubusercontent.com/30478166/35187975-a602ff24-fdfb-11e7-9cf8-a7a606aa3d35.jpeg)
the other 2 being related to line 368 where it says "wait" and line 961 where it says "ADIS16448_IMU::InitSendable"
![image1 1](https://user-images.githubusercontent.com/30478166/35188005-f4b781bc-fdfb-11e7-862e-ba09215b9f9f.jpeg)
![image2 1](https://user-images.githubusercontent.com/30478166/35188007-f6e319b0-fdfb-11e7-9cd8-09c637632de7.jpeg)
does anyone else get these errors, if so how do we fix them because as of right now our gyro won't give us an angle.

**Comment by facepalmgamer** [comment]
Sorry, I do not know why the picture are upside down.

**Comment by juchong** [comment]
Hi there! It looks like you may not have re-indexed the database after opening the project. In Eclipse, right-click on the project and select Index > Rebuild". If you have the latest 2018 libraries installed, the errors should go away.

**Comment by facepalmgamer** [comment]
as i'm deploying the code to the robot as well as when i'm activating it in the console i am receiving this error:
ERROR  -61072  Unknown error status  InitAuto [SPI.cpp:293]
	at frc::SPI::InitAuto(int)
	at ADIS16448_IMU::ADIS16448_IMU(ADIS16448_IMU::Axis, ADIS16448_IMU::AHRSAlgorithm)
	at Robot::RobotInit()
	at frc::TimedRobot::StartCompetition()
	at main
	at __libc_start_main
other than that rebuilding it fixed the other errors

**Comment by PeterJohnson** [comment]
InitAuto() is being called with 0 as the parameter.  This isn't valid; it looks like the Java code calls InitAuto() with 8200 as the parameter, and the C++ code should be changed to match.

**Comment by juchong** [comment]
I'll check this as soon as I get home. I didn't realize the C++ code was throwing an error.

**Comment by juchong** [comment]
Even after changing the value to 8200, the error is still triggered. Newest commit should reflect the change
