### ISSUE TITLE
could not find ADIS16448

### ISSUE THREAD

**Issue by floogulinc** [juchong/ADIS16448-RoboRIO-Driver#3]
When trying to use the java library, it fails to initialize giving this error to the driver station `ERROR 1 could not find ADIS16448`. I tried making it delay a bit before initializing it but it still doesn't work. The green light is on the unit and it appears to be connected.

**Comment by juchong** [comment]
Hi! I would check the connector on the RoboRIO and on the IMU itself to
make sure none of the pins are offset. When initializing, the MXP SPI port
should be selected.

Let me know if this helps!
-Juan

On Monday, April 4, 2016, Paul Friederichsen notifications@github.com
wrote:

> When trying to use the java library, it fails to initialize giving this
> error to the driver station ERROR 1 could not find ADIS16448. I tried
> making it delay a bit before initializing it but it still doesn't work. The
> green light is on the unit and it appears to be connected.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/juchong/ADIS16448-RoboRIO-Driver/issues/3

## 

_Juan Jose Chong_

http://www.juanjchong.com/
juanjchong@gmail.com
Mobile: (830)-968-3706

**Comment by floogulinc** [comment]
@juchong it is installed correctly and screwed in. After using a tweak of the code to give the SPI a little more time to work (https://github.com/FRC5333/2016-Stronghold/blob/master/src%2Fmain%2Fjava%2Ffrc%2Fteam5333%2Flib%2Fdevice%2FADIS16448_IMU.java#L110-L162) it does not give the same error most of the time but the IMU still doesn't function. It may be a hardware issue though.

**Comment by floogulinc** [comment]
Update: With that fix i gave, it seems to initialize ok. But now the gyro display on smartdashboard that used to show direction on the ground now seems to show angle perpendicular to the ground.

**Comment by juchong** [comment]
I don't think this feature has been built into the Java version of the
driver, but the sensor was initially written with the RoboRIO in the
horizontal orientation (Z axis going through the sensor's PCB). The LabVIEW
version of the driver allows for selecting the axis used for calculations.

On Mon, Apr 4, 2016 at 5:08 PM, Paul Friederichsen <notifications@github.com

> wrote:
> 
> Update: With that fix i gave, it seems to initialize ok. But now the gyro
> display on smartdashboard that used to show direction on the ground now
> seems to show angle perpendicular to the ground.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/juchong/ADIS16448-RoboRIO-Driver/issues/3#issuecomment-205498364

## 

_Juan Jose Chong_

http://www.juanjchong.com/
juanjchong@gmail.com
Mobile: (830)-968-3706

**Comment by floogulinc** [comment]
Yeah, it seems the Java version is setup for the Y axis to be the one going through the PCB, but it's actually the Z axis. Also, the delay with initializing is still an issue. i have to manually go and "Reboot Robot Code" in the dashboard after starting or resetting the robot to get the imu to work and I have the fix in the above posts as well as a 6 second delay.

**Comment by juchong** [comment]
Unfortunately the Java/C++ code has not been updated to incorporate all the LabVIEW updates. I'm currently working with others in the community to update the driver.

**Comment by alice15311** [comment]
I also have something to say.
