### ISSUE TITLE
Failing to detect Gyro, and ReadRegister returning 9.

### ISSUE THREAD

**Issue by TheHeadHornet2603** [juchong/ADIS16448-RoboRIO-Driver#31]
Trying to use the the Gryoscope fails to open it, returning 9 or 0 in the open function after running ReadRegistry for the product ID. I'm using the labview version of the example code. Do you think there's something wrong with the gyro, expansion board, or just RoboRio?

**Comment by TheHeadHornet2603** [comment]
I'm not sure if the gyro is broken or if there's something we're doing wrong in the code or something.

**Comment by juchong** [comment]
Hi @TheHeadHornet2603! Are you using the most up-to-date library? Did you install the library using the installer on the release page?
