### ISSUE TITLE
Missing Calibration VI

### ISSUE THREAD

**Issue by FRC-3277** [juchong/ADIS16448-RoboRIO-Driver#35]
<img width="352" alt="2019-02-14 17_39_35-ni example finder" src="https://user-images.githubusercontent.com/10522841/52824820-d4c26400-307f-11e9-8517-ab9fc2f90c97.png">

**Comment by juchong** [comment]
Hi, the calibration VI isn't missing. It was purposely removed this season since offset calibration is performed at runtime.
