### ISSUE TITLE
First pass delta T for calculation

### ISSUE THREAD

**Issue by brhea** [juchong/ADIS16448-RoboRIO-Driver#4]
Thanks for supporting this driver. I note in the latest copy you've fixed the bug related to the reset and improved the AHR calc!

In the loop I note that on first pass of the WPI_IMP_loop.vi the deltaT is calculated by subtracting 0 from the timestamp from the Interrupt Wait vi. E.G. the shift register is initialized to 0. Could this cause a very large deltaT on first pass and introduce significant error in the accumulator. Instead of initializing to 0 should this be initialized to a timestamp so it will be in the same basis as the output of the Interrupt Wait VI?

![capture](https://cloud.githubusercontent.com/assets/18398507/14428357/be10a06a-ffc6-11e5-91ca-dba9783d16ee.PNG)

**Comment by juchong** [comment]
Hi! Thanks for pointing this out! You're correct, the first dt calculated would cause significant error. The shift register should be initialized with the RoboRIO's time stamp function instead. I have made the correction and pushed an update which should resolve the issue.
