### ISSUE TITLE
No code after java deploy (2020 beta 4) with 2019-r3 library

### ISSUE THREAD

**Issue by ngreen-gt** [juchong/ADIS16448-RoboRIO-Driver#40]
I could deploy code after removing the library and switching to the SPI gyro.  I haven't tried more than the new ramsetecommand, which uses the wpilib Gyro class.

Saw only this in RIOlog:

java.io.IOException: opencv_java344 could not be loaded from path or an embedded resource.
attempted to load for platform /linux/athena/
at edu.wpi.first.wpiutil.RuntimeLoader.loadLibraryHashed(RuntimeLoader.java:125)
at edu.wpi.cscore.CameraServerJNI.<clinit>(CameraServerJNI.java:40)
at edu.wpi.first.wpilibj.RobotBase.startRobot(RobotBase.java:213)
at frc.robot.Main.main(Main.java:27)

Not sure how it could relate to the ADIS16448 library, but haven't had the problem after removing it.

**Comment by ThadHouse** [comment]
Because of the way this library was linked, 2019 versions will not work in 2020. I updated the build to make this not the case in the future, but it is a side effect of the 2019 build setup.
