### ISSUE TITLE
Object data types don't match between VIs

### ISSUE THREAD

**Issue by ryannazaretian** [juchong/ADIS16448-RoboRIO-Driver#5]
I'm finding some issues between some of the VIs where they use an older non-type def control that are incompatible with other VIs.

For example, the Open and Refnum Set functions are incompatible.

![image](https://cloud.githubusercontent.com/assets/1508222/16699476/73ea87ca-4522-11e6-8de6-1e0043dee7a8.png)

Looks like you created type-defs after-the-fact and may have forgotten to update some or commit them to GitHub.

**Comment by juchong** [comment]
Ooops! They're not used in the example program, so it looks like I broke them when adding the calibration feature. I'll take care of this.

**Comment by juchong** [comment]
Fixed with current revision.
