### ISSUE TITLE
WPI_IMU_ADIS16448_Open.vi - invalid selection for Netcom Resource Type

### ISSUE THREAD

**Issue by ryannazaretian** [juchong/ADIS16448-RoboRIO-Driver#6]
The use of ADIS16448 is an invalid Netcom Resource Type. 

![image](https://cloud.githubusercontent.com/assets/1508222/16699323/811f2118-4521-11e6-8022-12c386377ba7.png)

**Comment by juchong** [comment]
Sorry about that! NI has assigned the resource and ID, but it hasn't been pushed in a team update yet. Usage reporting will remain disabled until the resource update is pushed publicly.
